### ISSUE TITLE
Unable to use extends

### ISSUE THREAD

**Issue by jsebrech** [joost-de-vries/sbt-tslint#3]
I'm trying to use sbt-tslint in combination with extends in tslint.json.

I've tried extends "tslint:recommended", but while this executes it doesn't pick up any of the rules.

An alternative would be the microsoft recommended rules, but I don't know what extends value to use for that.

Thanks for any suggestions.

**Comment by joost-de-vries** [comment]
It [seems](https://github.com/palantir/tslint/commits/master/src/configs/recommended.ts) that `tslint:recommended` is a recent feature. 
I've created `sbt-tslint` version `3.15.1`. See if that fixes it.

**Comment by jsebrech** [comment]
I upgraded to sbt-tslint 4.0.2, ran activator clean, then when I run and load up a typescript file in the browser (using your sbt-typescript plugin combined with sbt-tslint) I get this error:

play.sbt.PlayExceptions$UnexpectedException: Unexpected exception[JsTaskFailure: C:\Develop\sumorea\repo\trunk\play\mercury\target\tslint\tslint.js:53
                var linter = new Tslint(sourceFile, source,jsLintOptions);
                             ^

TypeError: Tslint is not a constructor

Any thoughts?

**Comment by joost-de-vries** [comment]
Tslint 4.02 is obviously a major version upgrade. I think I'll delete that version until I've fixed the issue that you mention.
How about 3.15.1?

**Comment by jsebrech** [comment]
Error:Unresolved dependencies:<ul><li> name.de-vries#sbt-tslint;3.15.1: not found</li></ul>See complete log in <a href="C:\Users\js\.IntelliJIdea2016.3\system\log\sbt.last.log">C:\Users\js\.IntelliJIdea2016.3\system\log\sbt.last.log</a>

The log says:
[warn] 	module not found: name.de-vries#sbt-tslint;3.15.1
[warn] ==== typesafe-ivy-releases: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/name.de-vries/sbt-tslint/scala_2.10/sbt_0.13/3.15.1/ivys/ivy.xml
[warn] ==== sbt-plugin-releases: tried
[warn]   https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/name.de-vries/sbt-tslint/scala_2.10/sbt_0.13/3.15.1/ivys/ivy.xml
[warn] ==== local: tried
[warn]   C:\Users\js\.ivy2\local\name.de-vries\sbt-tslint\scala_2.10\sbt_0.13\3.15.1\ivys\ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/name/de-vries/sbt-tslint_2.10_0.13/3.15.1/sbt-tslint-3.15.1.pom

**Comment by joost-de-vries** [comment]
Ugh. I made an error writing the version. It should've been 3.15.1 just like the tslint version. But it's 3.5.1 right now. Sorry about that.
Btw you can find out about available versions right [here](https://bintray.com/joost-de-vries/sbt-plugins/sbt-tslint)

I guess I shouldn't rush new releases late at night...

**Comment by jsebrech** [comment]
I know that feeling :)

Anyway, I tried 3.5.1 and it still doesn't pick up on the tslint:recommended ruleset. I'm trying with the curly rule, it should trigger an error, but it doesn't unless I explicitly define it in my tslint.json.

**Comment by joost-de-vries** [comment]
Ok I've created a proper release of `3.15.1`. So that's the latest stable release right now.
Also I've replicated your problem: it seems values of `extends` need to be resolved and merged with the rest of the config _before_ the config is handed to the linter. 
Want to take a stab at that?

**Comment by joost-de-vries** [comment]
Cool.
I've added a unit test and published a new version `3.15.1-1`.
Tx man.

**Comment by jsebrech** [comment]
Thanks. I'll try out the new build on monday. Happy to help.
